### ISSUE TITLE
'not found' error is not helpful

### ISSUE THREAD

**Issue by NickHeiner** [marcelduran/webpagetest-api#13]
I'm using the `spec` feature to automatically run a test and compare it against a range of values. It's pretty slick, but I'm getting the following error:

```

  1) WebPageTest median.firstView.requests:
     Error: not found
      at /Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/specs.js:126:51
      at Array.forEach (native)
      at traverse (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/specs.js:117:24)
      at /Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/specs.js:131:9
      at Array.forEach (native)
      at traverse (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/specs.js:117:24)
      at /Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/specs.js:131:9
      at Array.forEach (native)
      at traverse (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/specs.js:117:24)
      at WebPageTest.specsRunner (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/specs.js:153:5)
      at callbackYield (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/webpagetest.js:128:14)
      at Function.asyncParserCallback (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/webpagetest.js:134:3)
      at /Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/helper.js:59:5
      at Parser.<anonymous> (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/node_modules/xml2js/lib/xml2js.js:368:20)
      at Parser.EventEmitter.emit (events.js:95:17)
      at Object.saxParser.onclosetag (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/node_modules/xml2js/lib/xml2js.js:338:24)
      at emit (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
      at emitNode (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
      at closeTag (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
      at Object.write (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/node_modules/xml2js/node_modules/sax/lib/sax.js:1293:29)
      at Parser.exports.Parser.Parser.parseString (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/node_modules/xml2js/lib/xml2js.js:386:29)
      at Parser.parseString (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/node_modules/xml2js/lib/xml2js.js:6:61)
      at Object.xmlToObj (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/helper.js:53:10)
      at WebPageTest.apiCallback (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/webpagetest.js:184:29)
      at unzip (/Users/nick.heiner/opower/x-web-frontend-perf-check/node_modules/webpagetest/lib/webpagetest.js:105:15)
      at Unzip.onEnd (zlib.js:166:5)
      at Unzip.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickDomainCallback (node.js:459:13)
```

My spec is:

``` json
{
    "median": {
        "firstView": {
            "requests": 200,
            "render": 4000,
            "loadTime": 30000
        }
    }
}
```

With some debugging, I found that it's because the webpagetest.org api isn't returning the path my spec wants to make an assertion about. (Frustratingly, this only happens intermittently, but that's another issue.) It would be nice if the error message were something more descriptive, like: 

``` js
tests.push({text: path.join('.'), result: new Error('Spec path `' + path.join('.') +
    '` not found in webpagetest results response `' + JSON.stringify(data) + '`'});
```

Additionally, I would recommend using substack's excellent [js-traverse](https://github.com/substack/js-traverse) to simplify the code in this area somewhat.

**Comment by reustmd** [comment]
@marcelduran I'm seeing this issue as well. fwiw, I only see it on linux, not on my mac.

any plans to look into this?
