### ISSUE TITLE
Cannot retrieve waterfall image - TypeError('invalid data') thrown in net.js

### ISSUE THREAD

**Issue by teamaton** [marcelduran/webpagetest-api#60]
Environment:
`node -v` -> `v4.2.2`
`npm -v` -> `2.9.1`

Here's the command I'm executing:

    webpagetest.cmd waterfall 151106_M0_P5Z

Here's the error I'm getting:

    net.js:617
        throw new TypeError('invalid data');
        ^

    TypeError: invalid data
        at WriteStream.Socket.write (net.js:617:11)
        at output (C:\Users\Oliver\AppData\Roaming\npm\node_modules\webpagetest\bin\webpagetest:27:18)
        at Function.formatData (C:\Users\Oliver\AppData\Roaming\npm\node_modules\webpagetest\bin\webpagetest:68:5)
        at callbackYield (C:\Users\Oliver\AppData\Roaming\npm\node_modules\webpagetest\lib\webpagetest.js:138:14)
        at WebPageTest.apiCallback (C:\Users\Oliver\AppData\Roaming\npm\node_modules\webpagetest\lib\webpagetest.js:207:7)
        at IncomingMessage.onEnd (C:\Users\Oliver\AppData\Roaming\npm\node_modules\webpagetest\lib\webpagetest.js:123:11)
        at emitNone (events.js:72:20)
        at IncomingMessage.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:905:12)
        at doNTCallback2 (node.js:441:9)

**Comment by bigethan** [comment]
Sometimes webpagetest doesn't make all the images - were you able to access the image by it's url from the response json?

**Comment by 0liver** [comment]
Yes, the images were there when I accessed them through the browser.
