### ISSUE TITLE
Unable to run sitespeed.io command - Didnt get URL's issue

### ISSUE THREAD

**Issue by badrinathvm** [marcelduran/webpagetest-api#68]
facing below error 

sitespeed.io -u http://www1.macys.com/shop/product/american-living-cap-sleeve-ruffled-dress?ID=1358999 -d 0 -b chrome -n 3
info: OS: 'darwin 14.3.0', Node.js: 'v4.2.2', sitespeed.io: '3.2.5', PhantomJS: '1.9.8', java: '1.7.0_75', browsertime: '0.9.3'
info: Will crawl from start point http://www1.macys.com/shop/product/american-living-cap-sleeve-ruffled-dress?ID=1358999 with crawl depth 0
error: Error from the crawl: The start url: http://www1.macys.com/shop/product/american-living-cap-sleeve-ruffled-dress?ID=1358999 couldn't be fetched, response code 401

info: Didn't get any URLs
error:  Error: No URLs to analyze
    at Object.module.exports.fineTuneUrls (/usr/local/lib/node_modules/sitespeed.io/lib/util/util.js:341:13)
    at /usr/local/lib/node_modules/sitespeed.io/lib/analyzeOneSite.js:50:12
    at fn (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/sitespeed.io/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by bigethan** [comment]
You probably know this, but `401` is unauthorized - somethings not accepting you somewhere in the line.  But this issue should be in sitespeed's repo, no?
