### ISSUE TITLE
median.firstView.score_gzip - Error: not found

### ISSUE THREAD

**Issue by hbokh** [marcelduran/webpagetest-api#73]
When using this command: `webpagetest test http://example.com --first --poll --specs testspecs.json` and this `testspecs.json`:
```
{
  "median": {
    "firstView": {
      "requests": 20,
      "render": 400,
      "loadTime": 3000,
      "score_gzip": {
        "min": 50
      }
    }
  }
}
```
I get this error:

```
2) WebPageTest median.firstView.score_gzip:
     Error: not found
      at /usr/local/lib/node_modules/webpagetest/lib/specs.js:126:19
      at Array.forEach (native)
      at traverse (/usr/local/lib/node_modules/webpagetest/lib/specs.js:116:24)
      at /usr/local/lib/node_modules/webpagetest/lib/specs.js:134:9
      at Array.forEach (native)
      at traverse (/usr/local/lib/node_modules/webpagetest/lib/specs.js:116:24)
      at /usr/local/lib/node_modules/webpagetest/lib/specs.js:134:9
      at Array.forEach (native)
      at traverse (/usr/local/lib/node_modules/webpagetest/lib/specs.js:116:24)
      at WebPageTest.specsRunner (/usr/local/lib/node_modules/webpagetest/lib/specs.js:160:5)
```

The test is run with the latest WebPagetest API, installed with `npm install webpagetest -g`.
WPT Private Instance v2.19 is using a headless Chrome browser in Xvfb.

The error occurs both on Ubuntu 14.04
```
npm --version
1.3.10
nodejs --version
v0.10.25
```
and Mac OS X "El Capitan":
```
npm --version
3.8.6
node --version
v6.0.0
```
Seems to be related to #13 
Any clues / hints / etc.?

**Comment by hbokh** [comment]
Seems to be related to **not** using an external Windows-based client.
I've set one up and the error did not occur anymore. Instead
` ✓ median.firstView.score_gzip: 100 should be greater than 50`.
Will close the issue.
